export const CREATE_SHOPPING_CART_PRODUCT = 'CREATE_SHOPPING_CART_PRODUCT';
export const DELETE_SHOPPING_CART_PRODUCT = 'DELETE_SHOPPING_CART_PRODUCT';
export const EDIT_SHOPPING_CART_PRODUCT = 'EDIT_SHOPPING_CART_PRODUCT';
export const GET_SHOPPING_CART_PRODUCT = 'GET_SHOPPING_CART_PRODUCT';
export const GET_SHOPPING_CART_PRODUCTS = 'GET_SHOPPING_CART_PRODUCTS';
export const CLEAR_SHOPPING_CART_PRODUCTS = 'CLEAR_SHOPPING_CART_PRODUCTS';